# Use an official Node.js runtime as a parent image
FROM node:18.13.0 as build


WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @angular/cli

COPY . .

RUN ng build --configuration=production

FROM nginx:latest
COPY --from=build app/dist/doctor-service-front /usr/share/nginx/html

#COPY nginx.conf /etc/nginx/conf.d/default.conf


#COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

#COPY --from=build /path/to/angular/build/output /usr/share/nginx/html

EXPOSE 4200
